apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
spec:
  match:
    - excludedNamespaces:
        - kube*
        - openshift*
        - redhat*
        - rhods*
      processes:
        - '*'
  sync:
    syncOnly:
      - group: ""
        kind: Namespace
        version: v1
      - group: ""
        kind: Pod
        version: v1
