apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyNetworkPolicyModifications
metadata:
  name: denynetworkpolicymodifications
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups:
          - networking.k8s.io
        kinds:
          - NetworkPolicy
  parameters:
    global-policy:
      allowedGroups: ["network-policy-admins"]
      allowedUsers: []
